### ISSUE TITLE
講桌

### ISSUE THREAD

**Issue by sunflower519sf** [tyroneyeh/SeatingChart#1]
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFoAAABACAYAAACa5WD/AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAAc1JREFUeJzt2LFqwmAYheHzf0RB6eaVOInX4J6Lc3Z3EgdxayveQnsL2WwqxJp0sW3UxIL5PbHpeTalhY8XOZC4+XyeQW5ms9kEYRjure5D/guFJlFoEoUmUWgShSZRaBKFJlFoEoUmUWgShSZRaBKFJlFoEoUmCeo+4JLVagWzy7+FNE0xHA5JF13vrkObGQaDwcW/Wa/XpGuq0XSQKDSJQpMoNIlCkyg0iUKTKDSJQpPc9ZNhFEW/PvlFUUS6ppq7Dj0ajeo+wRtNB4lCkyg0iUKTKDSJQpMoNIlCkyg0iUKTKDSJQpME0+m07hsaq9/vo9frAQAsCO76Bd6f1Wq10O12vz/bbrdLarynsZIkSRaLxUMYhnsAMOfca91HNdTLZDKJvz5YmqYzAB81HtREezOb5b8w59wSQFzyD3KdNwDL/BfmnHvMsqxT00GNlGVZJ47j5/x3Nh6P37XT3h3tM3B4YNFOe3W2z8AhtHbaq7N9Bn5Ca6c9Kdpn4BBaO+3V2T4DuZdK2mkvCvcZyIXWTntRuM/AcWjtdEVl+wzkQmunvSjcZ+Dkxb92upLSfQZOQmunKyndZ+Ak9Ha7fQLQvvVFDdUu22cRkSt9AicbkgadtfvPAAAAAElFTkSuQmCC

**Comment by tyroneyeh** [comment]
commit ac91fdc
